# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screen_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Input(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 293)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 20, 651, 181))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.source_video = QtWidgets.QLineEdit(self.frame)
        self.source_video.setGeometry(QtCore.QRect(10, 30, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.source_video.setFont(font)
        self.source_video.setReadOnly(True)
        self.source_video.setObjectName("source_video")
        self.Button_browse_Video = QtWidgets.QPushButton(self.frame)
        self.Button_browse_Video.setGeometry(QtCore.QRect(520, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_browse_Video.setFont(font)
        self.Button_browse_Video.setObjectName("Button_browse_Video")
        self.source_pretrain_file = QtWidgets.QLineEdit(self.frame)
        self.source_pretrain_file.setGeometry(QtCore.QRect(10, 80, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.source_pretrain_file.setFont(font)
        self.source_pretrain_file.setReadOnly(True)
        self.source_pretrain_file.setObjectName("source_pretrain_file")
        self.Button_pretrain = QtWidgets.QPushButton(self.frame)
        self.Button_pretrain.setGeometry(QtCore.QRect(520, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_pretrain.setFont(font)
        self.Button_pretrain.setObjectName("Button_pretrain")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(160, 0, 381, 31))
        self.label_4.setObjectName("label_4")
        self.ButtonAddsource = QtWidgets.QPushButton(self.frame)
        self.ButtonAddsource.setGeometry(QtCore.QRect(10, 140, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ButtonAddsource.setFont(font)
        self.ButtonAddsource.setObjectName("ButtonAddsource")
        self.ButtonClose = QtWidgets.QPushButton(self.frame)
        self.ButtonClose.setGeometry(QtCore.QRect(470, 140, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ButtonClose.setFont(font)
        self.ButtonClose.setObjectName("ButtonClose")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.source_video.setPlaceholderText(_translate("MainWindow", "Select Video for detection"))
        self.Button_browse_Video.setText(_translate("MainWindow", "BROWSE"))
        self.source_pretrain_file.setPlaceholderText(_translate("MainWindow", "Press browse to select best.pt pretrain"))
        self.Button_pretrain.setText(_translate("MainWindow", "BROWSE"))
        self.label_4.setText(_translate("MainWindow", "AUTO ANNOTATOR ALL IMAGES USING PRETRAIN IMAGE "))
        self.ButtonAddsource.setText(_translate("MainWindow", "ADD Source"))
        self.ButtonClose.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Input()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
