# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videodetect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Video(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1308, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 910, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lbl_video = QtWidgets.QLabel(self.centralwidget)
        self.lbl_video.setGeometry(QtCore.QRect(0, 0, 1301, 841))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_video.setFont(font)
        self.lbl_video.setAutoFillBackground(False)
        self.lbl_video.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.lbl_video.setText("")
        self.lbl_video.setScaledContents(False)
        self.lbl_video.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_video.setObjectName("lbl_video")
        self.video_name = QtWidgets.QLabel(self.centralwidget)
        self.video_name.setGeometry(QtCore.QRect(400, 770, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.video_name.setFont(font)
        self.video_name.setAlignment(QtCore.Qt.AlignCenter)
        self.video_name.setObjectName("video_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1308, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.SelectVideo = QtWidgets.QAction(MainWindow)
        self.SelectVideo.setObjectName("SelectVideo")
        self.actionSelect_Best_pt = QtWidgets.QAction(MainWindow)
        self.actionSelect_Best_pt.setObjectName("actionSelect_Best_pt")
        self.StartDetection = QtWidgets.QAction(MainWindow)
        self.StartDetection.setObjectName("StartDetection")
        self.Exit = QtWidgets.QAction(MainWindow)
        self.Exit.setObjectName("Exit")
        self.actionselectvideo = QtWidgets.QAction(MainWindow)
        self.actionselectvideo.setObjectName("actionselectvideo")
        self.startdetect = QtWidgets.QAction(MainWindow)
        self.startdetect.setObjectName("startdetect")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.actionSelectVideo = QtWidgets.QAction(MainWindow)
        self.actionSelectVideo.setObjectName("actionSelectVideo")
        self.actionStartDetect = QtWidgets.QAction(MainWindow)
        self.actionStartDetect.setObjectName("actionStartDetect")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "COPY@RIGHT : XUAN KY AUTOMATION - 17-3-2024   "))
        self.video_name.setText(_translate("MainWindow", "PICTURE OF OBJECT"))
        self.SelectVideo.setText(_translate("MainWindow", "SelectVideoSource"))
        self.actionSelect_Best_pt.setText(_translate("MainWindow", "Select Best.pt"))
        self.StartDetection.setText(_translate("MainWindow", "Start Video Detection"))
        self.Exit.setText(_translate("MainWindow", "Exit"))
        self.actionselectvideo.setText(_translate("MainWindow", "SelectVideo"))
        self.startdetect.setText(_translate("MainWindow", "StartDetect"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.actionSelectVideo.setText(_translate("MainWindow", "SelectVideo"))
        self.actionStartDetect.setText(_translate("MainWindow", "StartDetect"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Video()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
